// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aueba.Models;

namespace aueba.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210828014836_Game")]
    partial class Game
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("aueba.Models.Char", b =>
                {
                    b.Property<int>("CharID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11");

                    b.Property<int>("CharDex")
                        .HasColumnName("CharDex")
                        .HasColumnType("int(11)");

                    b.Property<int>("CharHP")
                        .HasColumnName("CharHP")
                        .HasColumnType("int(11)");

                    b.Property<string>("CharName")
                        .IsRequired()
                        .HasColumnName("CharName")
                        .HasColumnType("varchar(20")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_unicode_ci");

                    b.HasKey("CharID");

                    b.ToTable("Char");
                });
#pragma warning restore 612, 618
        }
    }
}
